language: python

python:
  - "3.6"

services:
  - postgresql

addons:
  - postgresql: "9.6"

env:
  global:
    - DATABASE_URL=postgres://user_name:user_password@localhost:5432/idiotransit_db

install: "pip install .[test]"

before_script:
  - psql -c "CREATE DATABASE idiotransit_db;" -U postgres
  - psql -c "CREATE USER user_name WITH PASSWORD 'user_password' CREATEDB;" -U postgres

script:
  - coverage run manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
